const Localizations = {
  'languages': [
    'ar', // Arabic
    'es', // Spanish
    'fr', // French
    'he', // Hebrew
    'hu', // Hungarian
    'id', // Indonesian
    'ms', // Malaysian
    'nl', // Dutch
    'sr', // Serbian
    'zh_CN' // Chinese Simplified
  ],
  'page-title': {
    'ar': 'بتكوين برايفت',
    'es': 'Bitcoin Private',
    'fr': 'Bitcoin Private',
    'he': 'Bitcoin Private',
    'hu': 'Bitcoin Private',
    'id': 'Bitcoin Private',
    'ms': 'Bitcoin Private',
    'nl': 'Bitcoin Private',
    'sr': 'Bitcoin Private',
    'zh_CN': 'Bitcoin Private'
  },
  'navigation-about': {
    'ar': 'عن',
    'es': 'Acerca de',
    'fr': 'A propos',
    'he': 'אודות',
    'hu': 'Rólunk',
    'id': 'Tentang',
    'ms': 'Tentang',
    'nl': 'Over ons',
    'sr': 'Osnovno',
    'zh_CN': '关于'
  },
  'navigation-hard-fork': {
    'ar': 'تقنية "الهارد فورك',
    'es': 'Hard Fork',
    'fr': 'Hard Fork',
    'he': 'פיצול',
    'hu': 'Hard Fork',
    'id': 'Hard Fork',
    'ms': 'Hard Fork',
    'nl': 'Hard Fork',
    'sr': 'Hard Fork',
    'zh_CN': '硬分叉'
  },
  'navigation-faq': {
    'ar': 'أسئلة متكررة',
    'es': 'Preguntas más frecuentes',
    'fr': 'FAQ',
    'he': 'שאלות נפוצות',
    'hu': 'GYIK',
    'id': 'Tanya Jawab',
    'ms': 'Soal Jawab',
    'nl': 'Veelgestelde vragen (FAQ)',
    'sr': 'Najčešće postavljana pitanja',
    'zh_CN': '常见问题'
  },
  'navigation-resources': {
    'ar': 'موارد',
    'es': 'Recursos',
    'fr': 'Ressources',
    'he': 'משאבים',
    'hu': 'Források',
    'id': 'Sumber-sumber',
    'ms': 'Sumber',
    'nl': 'Bronnen',
    'sr': 'Resursi',
    'zh_CN': '资源'
  },
  'navigation-language': {
    'ar': 'العربية',
    'es': 'Español',
    'fr': 'Français',
    'he': 'עִבְרִית',
    'hu': 'magyar nyelv',
    'id': 'Bahasa Indonesia',
    'ms': 'Malay',
    'nl': 'Nederlands',
    'sr': 'српски',
    'zh_CN': '简体中文'
  },
  'hero-blurb': {
    'ar': '"بتكوين برايفت"  تهتم بالخصوصية، غير متمركزة، سريعة، مفتوحة المصدر عملة قائمة على عامة المستخدمين ',
    'es': 'privado, descentralizado, rápido, de código abierto, moneda impulsada por la comunidad',
    'fr': 'Anonyme, décentralisé, rapide, open source, orienté par la communauté.',
    'he': 'פרטי, מבוזר, מהיר, קוד פתוח, מטבע המונע ע"י הקהילה',
    'hu': 'privát, decentralizált, gyors, nyílt forrású, közösség vezérelt érme',
    'id': 'koin privat, terdesentralisasi, cepat, sumber terbuka, dan berbasis komunitas',
    'ms': 'privasi, desentralisasi, pantas, sumber terbuka, syiling dipacu oleh komuniti',
    'nl': 'Privaat, gedecentraliseerd, snel, open source, community-gestuurde munt',
    'sr': 'Coin koji je privatan, decentralizovan, brz, otvorenog koda i vodjen zajednicom',
    'zh_CN': '私密，去中心化，高速，开源 社区主导的加密币'
  },
  'hero-coming-soon': {
    'ar': 'قادمة قريبا ',
    'es': 'Proximamente estaremos presentando mas información sobre el Hard Fork',
    'fr': 'Prochainement',
    'he': 'בקרוב מידע על',
    'hu': 'Hamarosan',
    'id': 'Segera Hadir',
    'ms': 'Akan Datang',
    'nl': 'Binnenkort',
    'sr': 'Uskoro dostupan',
    'zh_CN': '即将揭晓'
  },
  'hero-hard-fork-details': {
    'ar': 'تفاصيل تقنية "الهارد فورك"',
    'es': 'Hard Fork',
    'fr': 'Détails du Hardfork',
    'he': 'הפיצול',
    'hu': 'Hard Fork Részletek',
    'id': 'Detil Hard Fork',
    'ms': 'Butiran Hard Fork',
    'nl': 'Hard Fork Details',
    'sr': 'Detalji',
    'zh_CN': '硬分叉详情'
  },
  'why-btcp-header-title': {
    'ar': 'لماذا "بتكوين برايفت" ؟',
    'es': '¿Por qué $BTCP?',
    'fr': 'Pourquoi  BTCP?',
    'he': 'מדוע BTCP$?',
    'hu': 'Miért  $BTCP?',
    'id': 'Mengapa $BTCP?',
    'ms': 'Kenapa $BTCP?',
    'nl': 'Waarom $BTCP?',
    'sr': 'Zašto $BTCP?',
    'zh_CN': '为什么 $BTCP?'
  },
  'why-btcp-private-title': {
    'ar': 'خصوصية',
    'es': 'Privado',
    'fr': 'Anonyme',
    'he': 'פרטי',
    'hu': 'Privát',
    'id': 'Privat',
    'ms': 'Privasi',
    'nl': 'Privacy',
    'sr': 'Privatan',
    'zh_CN': '私密性'
  },
  'why-btcp-private-text': {
    'ar': '“بتكوين برايفت" ستستخدم ذات التقنية المستخدمة في عملة "زي كلاسيك" (الزي-سنارك). وهذا يعني أن الدفع يكون في الشبكة العامة وفي الوقت ذاته يكون المرسل ومعلوماته يبقون مجهولين.',
    'es': 'Bitcoin Private utilizará la misma tecnología de privacidad que ZClassic (zk-snarks). Esto significa que los pagos se publican en una cadena de bloques pública, pero el remitente, el destinatario y otros metadatos transaccionales permanecen inidentificables.',
    'fr': 'Bitcoin Private utilisera la même technologie anonyme que ZClassic (zk-snarks). Cela veut dire que les paiements seront publiés sur une blockchain publique, mais l\'expéditeur, le destinataire et toutes les autres metadata resteront non identifiables.',
    'he': 'Bitcoin Private תשתמש בטכנולוגיית הפרטיות של ZClassic (zk-snarks). משמעות הדבר היא שהתשלומים מתפרסמים על בלוק ציבורי, אך השולח, הנמען ומטה-נתונים אינם ניתנים לזיהוי.',
    'hu': 'A Bitcoin Private azonos titkosítási technológiát fog használni, mint a ZClassic (zk-snarks). Ez azt jelenti, hogy a fizetések nyilvános blokkláncon lesznek közzétéve; de a küldő, a címzett és más tranzakciós metaadat azonosíthatatlan marad.',
    'id': 'Bitcoin Private memakai teknologi privasi yang sama dengan ZClassic (zk-snarks). Ini artinya pembayaran akan dipublikasikan di blockchain umum, namun pengirim, penerima dan metadata transaksi lainnya tetap tersembunyi.',
    'ms': 'Bitcoin Private akan menggunakan teknologi privasi yang sama seperti ZClassic (zk-snarks). Ini bermakna maklumat bayaran akan dipaparkan pada blockchain awam, namun bagi maklumat penghantar, penerima dan transaksi metadata lain tetap dirahsiakan.',
    'nl': 'Bitcoin Private gebruikt privacy technologie zoals ZClassic (zk-snarks). Dit betekent dat betalingen worden gepubliceerd op een openbare blockchain, waarbij de zender, ontvanger en andere transactie metadata niet kunnen worden geïdentificeerd.',
    'sr': 'Bitcoin Private će koristiti istu tehnologiju za privatnost kao ZClassic (zk-snarks). Ovo znači da će transakcije bite objavljene na javnom blokčejnu (blockchain), ali pošiljalac novca, kao i onaj koji novac prima, a i sam iznos poslatog novca, ostaće nepoznati tj. anonimni.',
    'zh_CN': 'Bitcoin Private将使用和ZClassic (zk-snarks)同样的私密性技术。这意味着交易支付将会被公 布在公共区域链上，但是支付方、收款方、以及其他支付细节数据将会保持私密而无法被识别'
  },
  'why-btcp-decentralized-title': {
    'ar': ' غير متمركزة',
    'es': 'Descentralizado',
    'fr': 'Décentralisé',
    'he': 'מבוזר',
    'hu': 'Decentralizált',
    'id': 'Terdesentralisasi',
    'ms': 'Desentralisasi',
    'nl': 'Gedecentraliseerd',
    'sr': 'Decentralizovan',
    'zh_CN': '去中心化'
  },
  'why-btcp-decentralized-text': {
    'ar': 'تماما مثل بيتكوين، "بتكوين برايفت" ستدعم التحويلات بين المتعاملين فيها دون الحاجة إلى وسيط. وسيتم التحقق من هذه التحويلات في نقاط الالتقاء الشبكية من عن طريق التشفير وتسجيلها في السجل العام',
    'es': 'Al igual que Bitcoin, Bitcoin Private admitirá transacciones entre pares sin un intermediario. Estas transacciones serán verificadas por nodos de red mediante el uso de criptografía y registradas en un libro de contabilidad público.',
    'fr': 'Exactement comme le Bitcoin, le BTCP supportera les transactions peer-to-peer sans intermédiaire. Ces transactions seront vérifiées par des nodes de réseau grâce à l’utilisation de la cryptographie and seront enregistrées dans un registre public.',
    'he': 'בדיוק כמו Bitcoin מטבע ה-Bitcoin Private יתמוך בעסקאות "עמית-לעמית" ללא מתווך. עסקאות אלה יאומתו על ידי צמתי רשת באמצעים קריפטוגרפים וירשמו בספר החשבונות ציבורי (Public Ledger).',
    'hu': 'Pont mint a Bitcoin; a Bitcoin Private támogatja a “peer-to-peer” tranzakciókat közvetítő nélkül. Ezek a tranzakciók kriptográfiát használó hálózati csomópontok által lesznek ellenőrizve, hitelesítve és rögzítve nyilvános főkönyvben.',
    'id': 'Seperti Bitcoin, Bitcoin Private mendukung transaksi peer-to-peer tanpa pihak perantara. Transaksi-transaksi ini akan diverifikasi oleh node jaringan dengan menggunakan kriptografi dan tercatat dalam buku-besar umum.',
    'ms': 'Sama seperti Bitcoin, Bitcoin Private akan menyokong transaksi peer-to-peer tanpa perantara. Transaksi ini akan disahkan oleh nod rangkaian melalui penggunaan kriptografi dan direkodkan di dalam lejar awam.',
    'nl': 'Net als Bitcoin ondersteunt Bitcoin Private peer-to-peer transacties zonder een tussenpersoon. Deze transacties worden geverifieerd door netwerk nodes door gebruik te maken van cryptografie, en worden vastgelegd in een openbaar grootboek.',
    'sr': 'Poput Bitcoin-a, Bitcoin Private će podržavati peer-to-peer transakcije bez posrednika. Ove transakcije će biti verifikovane od strane “čvorova” (node) na mrži i obeležene u javnoj knjizi (ledger).',
    'zh_CN': '和比特币一样，Bitcoin Private支持无需中介的个人与个人之间直接交易。所有交易支付将会 通过密码学被各个网络节点验证并在公共记帐薄上存档。'
  },
  'why-btcp-fast-title': {
    'ar': 'سريعة',
    'es': 'Rápido',
    'fr': 'Rapide',
    'he': 'מהיר',
    'hu': 'Gyors',
    'id': 'Cepat',
    'ms': 'Pantas',
    'nl': 'Snel',
    'sr': 'Brz',
    'zh_CN': '高速'
  },
  'why-btcp-fast-text': {
    'ar': 'على خلاف عملة "البتكوين"، "بتكوين برايفت ستدعم الزيادة المتدرجة في حجم التحويلات وفي الوقت ذاته تزداد سريتها وأمنها المعلوماتي أكثر من أي عملة أخرى مبنية على "البتكوين" دون أي خسارة في سرعة التحويلات!',
    'es': 'A diferencia de Bitcoin, Bitcoin Private admitirá un tamaño de bloque modestamente aumentado a la vez que será más anónimo y seguro que cualquier divisa existente basada en Bitcoin sin sacrificar las velocidades de transacción.',
    'fr': 'Contrairement au Bitcoin, Bitcoin Private supportera une taille de block plus importante tout en restant plus anonyme et plus sécurisée que n’importe quelle monnaie basée sur le Bitcoin sans sacrifier la vitesse des transactions.',
    'he': 'שלא כמו ה-Bitcoin, מטבע ה-Bitcoin Private יתמוך בבלוק גדול יותר באופן מתון, ע"י היותו יותר אנונימי ומאובטח מאשר כל מטבע קיים אחר המבוסס על Bitcoin מבלי להקריב את מהירות העסקאות.',
    'hu': 'A Bitcoin-nal ellentétben, a Bitcoin Private támogat egy szerény mértékben megemelt blokkméretet, miközben sokkal nagyobb az anonimitása és biztonsága, mint bármely létező, a tranzakciós sebességet feláldozó Bitcoin-on alapuló kriptodevizának.',
    'id': 'Berbeda dengan Bitcoin, Bitcoin Private mendukung ukuran blok yang sedikit lebih besar namun tetap lebih anonim dan aman dari uang kripto berbasis Bitcoin lainnya tanpa mengurangi kecepatan transaksi.',
    'ms': 'Berbeza dengan Bitcoin, Bitcoin Private akan menyokong peningkatan saiz blok yang sederhana namun tetap lebih anonim dan selamat berbanding mana-mana mata wang kripto berasaskan Bitcoin sedia ada tanpa perlu mengorbankan kelajuan transaksi.',
    'nl': 'In tegenstelling tot Bitcoin ondersteunt Bitcoin Private een grotere block size en is deze tegelijkertijd anoniemer en veiliger dan welke Bitcoin-gebaseerde valuta dan ook, zonder in te boeten op de transactiesnelheid. ',
    'sr': 'Nasuprot Bitcoin-u, Bitcoin Private će podržavati umereno povećanj veličinu bloka dok će biti mnogo anonimniji i bezbedniji od bilo koje verzije Bitcoin-a koja trenutno postoji, što neće smanjiti brzinu transakcija.',
    'zh_CN': '与比特币不同，Bitcoin Private将支持更大的区块尺寸，并且在不影响交易速度的同时比目前 任何在比特币基础上发行的货币都更私密和安全。'
  },
  'why-btcp-open-source-title': {
    'ar': 'مفتوحة المصدر',
    'es': 'Fuente abierta',
    'fr': 'Open Source',
    'he': 'קוד פתוח',
    'hu': 'Nyílt forrású',
    'id': 'Sumber Terbuka',
    'ms': 'Sumber Terbuka',
    'nl': 'Open-Source',
    'sr': 'Otvorenog koda',
    'zh_CN': '开源'
  },
  'why-btcp-open-source-text': {
    'ar': 'كامل قاعدة بيانات "بتكوين برايفت" البرمجية مفتوح للعامة ويمكن الاطلاع عليها والتأكد منها في أي وقت. قاعدة البيانات البرمجية ستبقى مفتوحة المصدر لتمكن المطورون حول العالم من تحسينها والحفاظ عليها.',
    'es': 'Toda la base de código de Bitcoin Private está públicamente disponible para su visualización y verificación por cualquier persona. Siempre seguirá siendo de código abierto y será mantenido por una comunidad en constante crecimiento.',
    'fr': 'Le code base entier du BTCP est public et disponible pour être vu et vérifié par n’importe qui. Il restera toujours open source et sera entretenu par une communauté toujours grandissante.',
    'he': 'בסיס הקוד השלם של Bitcoin Private זמין לציבור לצפייה ולאימות על ידי כל אחד, הקוד תמיד יהיה "קוד פתוח" ויתוחזק על ידי הקהילה ההולכת וגדלה.',
    'hu': 'A Bitcoin Private teljes kódbázisa nyilvánosan elérhető, ellenőrizhető és megtekinthető bárki által. Mindig nyílt forrású marad és egy növekvő közösség által lesz fenntartva.',
    'id': 'Seluruh kode sumber Bitcoin Private terbuka untuk dilihat dan diverifikasi oleh siapa saja. Kode sumber ini akan tetap terbuka dan dikelola oleh komunitas yang terus berkembang.',
    'ms': 'Seluruh kod asas Bitcoin Private terbuka untuk tontonan dan pengesahan oleh sesiapa sahaja. Ia akan kekal sebagai sumber terbuka dan diuruskan oleh komuniti yang semakin berkembang.',
    'nl': 'Bitcoin Private’s volledige broncode is voor iedereen openbaar toegankelijk voor naslag en verificatie. Het blijft altijd open-source en zal onderhouden worden door een steeds groeiende community.',
    'sr': 'Kompletan kod Bitcoin Private-a je dostupan javnosti na pregled i verifikaciju od strane bilo koga. Uvek će ostati takav, otvorenog koda, i održavan od strane zajednice i time koji konstantno rastu.',
    'zh_CN': 'Bitcoin Private 的源代码公开供所有人浏览和验证。该源代码将永远保持开源，由一个不断壮 大的社区共同维护。'
  },
  'why-btcp-community-driven-title': {
    'ar': 'قائمة على عامة المستخدمين',
    'es': 'Impulsado por la comunidad',
    'fr': 'Orienté par la communauté',
    'he': 'מונע קהילה',
    'hu': 'Közösség által vezérelt',
    'id': 'Berbasis Komunitas',
    'ms': 'Dipacu Oleh Komuniti',
    'nl': 'Community-gestuurd',
    'sr': 'Vodjen zajednicom',
    'zh_CN': '社区主导'
  },
  'why-btcp-community-driven-text': {
    'ar': 'إن هذه العملة تتصف بالشفافية، فهي مطورة من قبل مطورين من جميع أنحاء الأرض. كل عضو يملأ فراغ ويشارك بناءً على خبراته ومهاراته.',
    'es': 'En la naturaleza de la transparencia y el código abierto, Bitcoin Private es desarrollado por miembros del equipo en todo el mundo. Cada miembro llena roles y contribuye según sus conjuntos de habilidades.',
    'fr': 'Dans l’esprit de la transparence et de l’open source, Bitcoin Private est développé par des membres de l’équipe dans le monde entier. Chaque membre remplit son rôle et contribue en fonction de ses compétences.',
    'he': 'תפיסת העולם שלנו היא: שקיפות וקוד פתוח. Bitcoin Private פותח על ידי חברי צוות מכל רחבי העולם. כל חבר ממלא תפקיד ותורם על סמך כישוריו.',
    'hu': 'Az átláthatóság és nyílt forrás természeténél fogva, a világ különböző pontjairól származó csapat fejlesztette a Bitcoin Private-et. Ehhez minden csapattag a képességeihez mérten járul hozzá és végzi feladatát.',
    'id': 'Sesuai dengan transparansi dan keterbukaan, Bitcoin Private dikembangkan oleh tim yang berasal dari seluruh dunia. Setiap anggota berperan dan berkontribusi sesuai dengan keahliannya masing-masing.',
    'ms': 'Sesuai dengan sifat ketelusan dan keterbukaan, Bitcoin Private dibangunkan oleh ahli pasukan dari seluruh dunia. Setiap ahli mengisi peranan dan menyumbang sesuai dengan kemahiran masing-masing.',
    'nl': 'Met als kenmerken transparantie en open source is Bitcoin Private ontwikkeld door teamleden van over de hele wereld. Elk teamlid vervult een rol en draagt bij op basis van zijn of haar expertise.',
    'sr': 'Po prirodi transparentan i otvorenog koda, Bitcoin Private je razvijen od strane tima čiji članovi dolaze sa svih strana sveta. Svaki član ispunjava svoju ulogu i doprinosi u skladu sa svojim veštinama.',
    'zh_CN': '源于其透明和开源的属性，Bitcoin Private由来自全世界的开发团队共同开发。每个团队成员 根据他们自己的技能分担不同的职能来对项目做出贡献。'
  },
  'why-btcp-fair-start-title': {
    'ar': 'بداية عادلة',
    'es': 'Un buen comienzo',
    'fr': 'Un juste départ',
    'he': 'התחלה הוגנת',
    'hu': 'Igazságos kezdet',
    'id': 'Awal yang adil',
    'ms': 'Permulaan Yang Adil',
    'nl': 'Een eerlijk begin',
    'sr': 'Fer start',
    'zh_CN': '公平的起点'
  },
  'why-btcp-fair-start-text': {
    'ar': 'لن يكون هناك ضريبة ولا إتاوة مؤسس. سيتم اطلاق سراح "بيتكوين برايفت" بطريقة عادلة للجميع. وسيتم توزيع النقود بنسبة ١ إلى ١أي لكل حامل عملة "بتكوين" أو "زيكلاسيك" عملة "بتكوين برايفت" واحدة.',
    'es': 'No habrá premonición ni recompensa de fundador. Bitcoin Private se lanzará de manera justa para todos. Las monedas se distribuirán en una base 1: 1 a titulares de BTC y ZCL.',
    'fr': 'Il n’y aura pas de pré-minage, et aucune récompense pour les fondateurs. Le Bitcoin Private sera distribué d’une manière juste pour tous. Les coins seront distribués sur la base de 1 pour 1 pour tous les détenteurs de BTC et de ZCL.',
    'he': 'לא תהיה חציבה מוקדמת ולא פיצוי מייסדים. Bitcoin Private ישוחרר בצורה הוגנת לכל. המטבעות יחולקו על בסיס 1:1 לכל מחזיקי מטבעות ה-BTC וה-ZCL.',
    'hu': 'Nem lesz elő-bányászat és nincs jutalom / bónusz az alapítóknak. A Bitcoin Private kibocsájtás igazságos módon történik mindenkinek. Az érmék 1:1 arányban lesznek kiosztva a már meglévő BTC és ZCL alapján a tulajdonosaiknak.',
    'id': 'Tidak ada premine, dan tidak ada keuntungan khusus untuk pendiri. Bitcoin Private akan dirilis dengan cara yang adil untuk semua. Koin akan didistribusikan dengan basis 1:1 terhadap pemilik BTC dan ZCL.',
    'ms': 'Tidak ada pralombong, dan tidak ada ganjaran khusus untuk pengasas. Bitcoin Private akan dilancarkan secara adil untuk semua. Syiling akan diedarkan pada asas 1:1 untuk semua pemilik BTC dan ZCL.',
    'nl': 'Er zal geen pre-mine periode zijn en er is geen beloning voor de oprichters. Bitcoin Private wordt gelanceerd op een eerlijke manier voor iedereen. De munt zal op een 1:1 basis worden gedistribueerd aan houders van BTC en ZCL.',
    'sr': 'Nema “premine” i nema nadoknade za osnivače. Bitcoin Private će biti podjednako day svima. Coin će biti dodjeljivan na bazi 1:1 svim ljudima koji u trenutku hard forka poseduju BTC ili ZCL.',
    'zh_CN': '没有预先挖矿，没有创始人奖励。Bitcoin Private的发放将对所有人保持公平。Bitcoin Private 将会按照1:1的比例对持有比特币和ZCL的持币人发放。'
  },
  'why-btcp-whitepaper-button': {
    'ar': 'ويتيبابر قريبا',
    'es': 'documento técnico está por llegar',
    'fr': 'livre blanc arrive bientôt',
    'he': 'נייר לבן בקרוב',
    'hu': 'hamarosan fehér papír készül',
    'id': 'whitepaper akan segera hadir',
    'ms': 'whitepaper akan datang tidak lama lagi',
    'nl': 'whitepaper komt binnenkort',
    'sr': 'ускоро ће се појавити беле боје',
    'zh_CN': '白皮书即将推出'
  },
  'hard-fork-header-title': {
    'ar': '"هارد فورك"',
    'es': 'Hard Fork',
    'fr': 'Hard Fork',
    'he': 'פיצול',
    'hu': 'Hard Fork',
    'id': 'Hard Fork',
    'ms': 'Hard Fork',
    'nl': 'Hard Fork',
    'sr': 'Hard Fork',
    'zh_CN': '硬分叉'
  },
  'hard-fork-what-is-title': {
    'ar': 'ماهية تقنية “هارد فودك” ؟',
    'es': '¿Qué es un Hard Fork?',
    'fr': 'Qu’est ce qu’un hard-fork ?',
    'he': 'מהו הפיצול?',
    'hu': 'Mi az a “hard fork”?',
    'id': 'Apa itu hard fork?',
    'ms': 'Apa itu hard fork?',
    'nl': 'Wat is een Hard Fork?',
    'sr': 'Šta je hard fork?',
    'zh_CN': '什么是硬分叉？'
  },
  'hard-fork-what-is-text': {
    'ar': 'عملية انقسام عملة إلكترونية  لقسمين تدعى “هارد فورك”. تحدث هذه العملية عندما تتغير شيفرة العملة وتصنع نسخة جديدة مضافة للأصلية. هذه الحالة فريدة بنوعها حيث أن عملة “بتكوين” و”زيكلاسيك” يتحدون لصنع “بتكوين برايفت',
    'es': 'Un Hard Fork es cuando una sola criptomoneda se divide en dos. Ocurre cuando se cambia el código existente de una criptomoneda, lo que da como resultado una versión antigua y una nueva. Este caso es algo único, por lo que ZCL y BTC se bifurcarán en Bitcoin Private (BTCP).',
    'fr': 'Un hard fork se produit quand une crypto-monnaie se divise en deux. Il se produit quand le code d’une crypto-monnaie est changé, ce qui donne le résultat d’une ancienne et d’une nouvelle version. Dans ce cas, il se produira quelque chose d’unique, puisque ZCL et BTC vont toutes deux co-produire le fork du Bitcoin Private (BTCP).',
    'he': 'הפיצול מתבצע כאשר מטבע כסף דיגיטלי מתחלק לשניים. המשמעות היא שהקוד הקיים של המטבע הדיגיטלי משתנה, וכתוצאה מכך נוצרת גרסה חדשה למטבע ישן. במקרה של Bitcoin Private הפיצול הינו ייחודי וכולל שני מטבעות דיגיטליים (Bitcoin  ו-ZClassic) אשר יתפצלו בצורה משותפת אל Bitcoin Private.',
    'hu': 'A “hard fork” az amikor egy kriptodeviza két felé szakad. Ez akkor következik be ha egy kriptodeviza már meglévő kódja kicserélődik, eredményezve egy régi és új verziót. Ebben az esetben valami mégis rendhagyó, a ZCL és BTC közös kettéválasztása (egy új kriptodevizába) a Bitcoin Private-be (BTCP).',
    'id': 'Hard fork adalah ketika suatu uang kripto terbagi menjadi dua. Ini terjadi ketika kode sumber uang kripto mengalami perubahan yang menyebabkan uang kripto tersebut terbagi menjadi versi lama dan versi baru. Fork ini berbeda dengan yang lain, dimana ZCL dan BTC akan mengalami fork bersama dan bergabung menjadi Bitcoin Private (BTCP).',
    'ms': 'Hard fork adalah apabila satu cryptocurrency tunggal berpisah kepada dua. Ia berlaku apabila kod mata wang kripto sedia ada diubah, mengakibatkan ia berpisah menjadi versi lama dan versi baru. Hal ini agak unik, di mana ZCL dan BTC akan fork bersama dan bergabung menjadi Bitcoin Private (BTCP).',
    'nl': 'Een hard fork ontstaat wanneer een cryptovaluta in tweeën splitst. Dit gebeurt wanneer de bestaande programmatuur van de munt wordt veranderd en dit resulteert in een oude en nieuwe versie van de munt. De hard fork van Bitcoin Private is een iets aangepaste variant, waarbij ZCL en BTC beide worden geforked in Bitcoin Private (BTCP).',
    'sr': 'Hard fork je kada se jedna kriptovaluta podeli na dvije. Ovo se dešava kada je kod postojeće kriptovalute izmijenjen, što rezultira u trenutoj i novoj verziji te valute. Slučaj BTCP-a je na neki način specifičan, jer će se dvije valute - ZCL i BTC zajedno forkovati u Bitcoin Private (BTCP).',
    'zh_CN': '当一个加密币一分为二时，被称为硬分叉。当硬分叉发生时，该加密币的源代码将被改动，进 而出现新和旧两个版本。此次Bitcoin Private硬分叉稍微独特，ZCL和比特币将会共同分叉而 产生Bitcoin Private (BTCP).'
  },
  'hard-fork-when-is-title': {
    'ar': 'متى تبدأ التقنية ؟',
    'es': '¿Cuándo es el Hard Fork?',
    'fr': 'Quand aura lieu le hard-fork ?',
    'he': 'מתי יתרחש הפיצול?',
    'hu': 'Mikor történik meg a “hard fork”?',
    'id': 'Kapan hard fork?',
    'ms': 'Bila hard fork akan terjadi?',
    'nl': 'Wanneer is de Hard Fork?',
    'sr': 'Kada će se desiti ovaj hard fork?',
    'zh_CN': '什么时候硬分叉？'
  },
  'hard-fork-when-is-text': {
    'ar': 'لا يوجد تاريخ محدد في الوقت الحالي. فريق "بتكوين برايفت" يعمل على مدار الساعة لإتمام العملية بنجاح وسيتم الإعلان قريباً.',
    'es': 'En este momento, no se ha anunciado una fecha oficial. El equipo de Bitcoin Private está trabajando incansablemente para tener todo listo para el inminente lanzamiento.',
    'fr': 'Pour l’instant aucune date officielle n’a été annoncée. L’équipe du BTCP est en train de travailler sans relâche pour faire en sorte que tout soit prêt pour une distribution imminente.',
    'he': 'בשלב זה, לא פורסם תאריך רשמי. צוות הפיתוח של ה-Bitcoin Private עובד ללא לאות כדי להיות מוכן לשחרור המטבע הממשמש ובא.',
    'hu': 'Jelenleg nincs hivatalos időpont kihirdetve. A Bitcoin Private csapata fáradhatatlanul dolgozik azon, hogy minden kész legyen a közelgő kibocsájtásra.',
    'id': 'Pada saat ini, belum ada tanggal resmi yang diumumkan. Tim Bitcoin Private bekerja sangat keras untuk menyiapkan agar segala sesuatunya siap untuk dirilis.',
    'ms': 'Pada masa ini, tiada tarikh rasmi diumumkan. Pasukan Private Bitcoin sedang bekerja keras untuk menyiapkan segala-galanya untuk pelancaran kelak.',
    'nl': 'Op dit moment is er nog geen officiële datum bekendgemaakt. Het Bitcoin Private team gaat onvermoeibaar door om alles klaar te maken voor de komende release.',
    'sr': 'Trenutno još nije objavljen zvaničan datum. Bitcoin Private tim vrijedno radi da bi sve bilo spremno za hard fork.',
    'zh_CN': '当前，硬分叉的官方时间还没有公布。Bitcoin Private团队正在不知疲惫地为即将到来的发布 一切就绪做准备。'
  },
  'hard-fork-receive-title': {
    'ar': 'كيف أحصل على "بيتكوين برايفت" ؟',
    'es': '¿Cómo recibo BTCP?',
    'fr': 'Comment vais-je recevoir mes BTCP?',
    'he': 'כיצד ניתן לקבל BTCP?',
    'hu': 'Hogyan kapom meg a BTCP-t?',
    'id': 'Bagaimana saya mendapat BTCP?',
    'ms': 'Bagaimana saya boleh mendapatkan BTCP?',
    'nl': 'Hoe ontvang ik BTCP?',
    'sr': 'Kako da dobijem BTCP?',
    'zh_CN': '如何获得BTCP?'
  },
  'hard-fork-receive-text': {
    'ar': 'بعد إتمام عملية "الهارد فورك" سيتم تسجيل كل عمل "زيكلاسك" و"بتكوين" وإعطاء "بتكوين برايفت" لكل حاملين لأحد هاتين العملتين داخل محفظة تدعم التداول بعدد مالديهم من عمل.',
    'es': 'Cuando se produce el Hard Fork, se producirá una imagen instantánea (Snapshot) de todas las direcciones existentes de ZCL y BTC. Cualquier persona que tenga ZCL o BTC en una billetera o en un intercambio admitido recibirá crédito de Bitcoin Private (BTCP) en una proporción de 1: 1. Por ejemplo, si tiene 15.4 ZCL, recibirá 15.4 BTCP.',
    'fr': 'Quand le hard-fork se produira, un snapshot de tous les ZCL and BTC sera réalisé. Quiconque détenant du ZCL ou du BTC dans un wallet ou sur un exchange supportant le hardfork sera crédité de Bitcoin Private (BTCP) pour un ratio d’1:1. A titre d’exemple, si vous possédez 15.4 ZCL, vous recevrez 15.4 BTCP.',
    'he': 'כאשר הפיצול יבוצע, תילקח תמונת מצב של ההחזקות במטבעות ZCL ו-BTC. כל אדם אשר יחזיק באחד מן המטבעות ZCL או BTC בארנק פרטי או בארנק באחת מן הבורסות המטבע שיתמכו יזוכה ב-Bitcoin Private (BTCP) ביחס של 1: 1. לדוגמה, במידה ואת/ה מחזיק/ה כמות של 15.4 מטבעות מסוג ZCL, תקבל/י 15.4 מטבעות מסוג BTCP.',
    'hu': 'Amikor a “hard fork” megtörténik, a pillanatnyi állás alapján az összes létező ZCL és BTC birtoklás rögzítve lesz. Bármennyi, a pénztárcában vagy támogatott kereskedő oldalon tárolt / birtokolt ZCL vagy BTC alapján 1:1 arányban lesz Bitcoin Private (BTCP) jóváírva. Például ha birtokolsz 15.4 ZCL-t, akkor 15.4 BTCP-t kapsz.',
    'id': 'Ketika hard fork terjadi, snapshot untuk semua ZCL dan BTC akan terjadi. Siapapun yang memiliki ZCL atau BTC di dompet atau bursa yang mendukung akan mendapatkan Bitcoin Private (BTCP) dengan rasio 1:1. Contoh, jika kamu memiliki 15.4 ZCL dan 0.1 BTC, kamu akan menerima 15.5 BTCP.',
    'ms': 'Apabila hard fork berlaku, snapshot dari semua pemilik ZCL dan BTC akan berlaku. Sesiapa yang memiliki ZCL atau BTC di dalam dompet atau bursa yang disokong akan dikreditkan Bitcoin Private (BTCP) pada nisbah 1:1. Sebagai contoh, jika anda memiliki 15.4 ZCL, anda akan menerima 15.4 BTCP.',
    'nl': 'Tijdens de hard fork wordt er een snapshot van de bestaande ZCL en BTC blockchain gemaakt. Iedereen die ZCL of BTC in een wallet, of op een ondersteunende exchange heeft, krijgt Bitcoin Private (BTCP) in een 1:1 ratio. Als voorbeeld: Indien je 15,4 ZCL en 0,1 BTC hebt, ontvang je 15,5 BTCP.',
    'sr': 'Kada se hard fork desi, biće uzet presek svih poseda ZCL i BTC. Svakome ko u tom trenutku bude posedovao ZCL i/ili BTC u wallet-u ili podržanom exchange-u biće dodeljeno Bitcoin Private (BTCP) u razmeru 1:1. Na primer, ukoliko posedujete 15.4 ZCL (ZClassic), dobićege 15.4 BTCP.',
    'zh_CN': '当硬分叉发生时，会对所有ZCL和比特币的持有进行一次快照(snapshot)。所有在钱包中或者 支持该硬分叉的交易平台上持有ZCL和比特币的持币者都会按照1:1的比例获得Bitcoin Private (BTCP)。例如：如果你持有15.4个ZCL, 你将会获得15.4个BTCP。'
  },
  'faq-header-title': {
    'ar': 'أسئلة متكررة',
    'es': 'Preguntas frecuentes',
    'fr': 'FAQ',
    'he': 'שאלות נפוצות',
    'hu': 'Gyakran Ismételt Kérdések',
    'id': 'Tanya Jawab',
    'ms': 'Soal Jawab',
    'nl': 'Vaak Gestelde Vragen (FAQ)',
    'sr': 'Često postavljana pitanja',
    'zh_CN': '常见问题'
  },
  'faq-who-runs-title': {
    'ar': 'من هم العاملين على هذا المشروع؟',
    'es': '¿Quién está ejecutando el proyecto?',
    'fr': 'Qui porte le projet ?',
    'he': 'מי מנהל את הפרויקט?',
    'hu': 'Kik vezetik a projektet?',
    'id': 'Siapa yang menjalankan proyek ini?',
    'ms': 'Siapa yang menjalankan projek ini?',
    'nl': 'Wie runt het project?',
    'sr': 'Ko je na čelu ovog projekta?',
    'zh_CN': '谁在运行这个项目？'
  },
  'faq-who-runs-text': {
    'ar': 'ريت كريتون هو المطور القائد للمشروع لكن بشكل عام المطورون حول العالم كثر حوالي ٥٠ مطور مشارك ألى الآن. إن هذا المشروع قائم على المشاركة وفي النهاية كلنا نعمل على إتمام المشروع في المستقبل القريب.',
    'es': 'Rhett Creighton es el desarrollador principal. En general, nuestro equipo de contribución es enorme, casi 50 miembros activos a partir de ahora. Este es un proyecto realmente impulsado por la comunidad y todos estamos interesados ​​en hacer que este fork sea un éxito y BTCP el futuro.',
    'fr': 'Rhett Creighton est le principal développeur. Par ailleurs, notre équipe de collaborateurs est considérable, et comprend environ 50 membres actifs pour le moment. C’est un véritable projet communautaire et nous sommes tous investis pour faire en sorte que ce fork se produise et pour que la réalisation du BTCP soit une réussite.',
    'he': 'Rhett Creighton הוא המפתח המוביל.  התמיכה בפיתוח היא ענקית, נכון לעכשיו הצוות מונה כמעט 50 חברים פעילים. זהו פרויקט שמונע ע"י הקהילה, ואנחנו עושים כל שביכולתנו להוציא לפעול את הפיצול ולגרום ל-BTCP להיות מטבע העתיד.',
    'hu': 'Rhett Creighton a vezető fejlesztő. Összességében a csapatunk jelentős méretű, majdnem 50 aktív tagja van eddig. Ez egy igazi, közösség által vezérelt projekt és mindannyian sokat fektettünk bele hogy a BTCP “fork” megtörténjen.',
    'id': 'Bitcoin Private adalah fork berbasis komunitas yang saat ini didukung oleh lebih dari 50 kontributor berbakat. Kami sepenuhnya transparan kepada komunitas dan selalu melibatkan komunitas dalam mengambil keputusan mengenai fork ini dan masa depan BitcoinPrivate.',
    'ms': 'Rhett Creighton adalah developer utama. Secara keseluruhannya, pasukan kami adalah sangat besar, hampir 50 orang ahli aktif pada masa ini. Ini adalah projek yang benar-benar didorong oleh komuniti, dan kita semua menyumbang dalam merialisasikan fork ini menjadi kenyataan dan BTCP masa depan.',
    'nl': 'Rhett Creighton is de hoofdontwikkelaar. Daarnaast is het bijdragende team enorm; bijna 50 actieve leden op dit moment. Het project is werkelijk community gestuurd en wij zijn allemaal betrokken om de hard fork en de toekomst van BTCP mogelijk te maken.',
    'sr': 'Ret Krigton (Rhett Creighton) je glavni programer. Sveukupno, naš tim je ogroman, sa skoro 50 aktivnih člankva koji doprinose ovom projektu. Ovo je projekat u potpunosti vodjen zajednicom, i svi smo beskrajno posvećeni tome da napravimo ovaj hard fork i BTCP.',
    'zh_CN': 'Rhett Creighton是项目主要开发者。总的来说，我们的开发贡献团队庞大，目前有大约50个 活跃的团队成员。这是一个真正属于社区主导的项目，我们所有人都做出了投入来确保硬分叉 的顺利发布和BTCP的未来成功。'
  },
  'faq-what-exchanges-title': {
    'ar': 'ماهي التداولات الداعمة لل"فورك"',
    'es': '¿Qué intercambios apoyarán el Hard Fork?',
    'fr': 'Quels exchanges vont supporter le fork?',
    'he': 'איזו בורסת מטבעות דיגיטליים תתמוך בפיצול?',
    'hu': 'Melyik kereskedőoldalak támogatják a “fork”-ot?',
    'id': 'Bursa apa yang mendukung fork ini?',
    'ms': 'Bursa apa yang menyokong fork ini?',
    'nl': 'Welke exchanges ondersteunen de fork?',
    'sr': 'Koji exchange-ovi (betze) će podržati fork?',
    'zh_CN': '哪些交易平台会支持这次分叉？'
  },
  'faq-what-exchanges-text': {
    'ar': 'حتى الآن نحن نتناقش مع متداولين أفراد في هذا الخصوص. لطفا تحلو بالصبر فحتى الأن لم نصرح بدعم أى تداول بعينه.',
    'es': 'A partir de ahora, estamos hablando activamente con intercambios individuales sobre este tema. Tengan paciencia, ya que todavía no estamos haciendo declaraciones sobre el apoyo de intercambios individuales.',
    'fr': 'Au jour d’aujourd’hui, nous sommes en train de discuter activement et individuellement avec les plateformes d’exchanges. Soyez patients s’il vous plait, nous ne pouvons faire aucune projection sur la décision des exchanges pour le moment.',
    'he': 'נכון לעכשיו, אנחנו מדברים באופן פעיל עם מספר בורסות מטבעות דיגיטליים בעניין זה יש להיות סבלניים, אנו מנהלים משא ומתן עם מספר בורסות, כרגע אין עדיין הצהרה רשמית לגבי תמיכה.',
    'hu': 'Jelenleg, aktív tárgyalásokat folytatunk az egyes kereskedőoldalakkal ezügyben. Kérlek légy türelemmel, mert jelenleg még nem jelenthetjük ki mely oldalak fogják támogatni.',
    'id': 'Kami terus berkomunikasi dengan bursa-bursa yang ada mengenai hal ini. Mohon bersabar, kami belum mengeluarkan pernyataan apapun mengenai dukungan dari bursa.',
    'ms': 'Setakat ini, kami secara aktif telah berbincang dengan banyak bursa tentang perkara ini. Mohon bersabar, kami belum membuat sebarang kenyataan mengenai sokongan daripada mana-mana bursa.',
    'nl': 'Op dit moment zijn wij actief aan het onderhandelen met diverse exchanges en doen wij geen uitspraken over ondersteuning van specifieke exchanges.',
    'sr': 'Trenutno smo u razgovorima sa exchange-ovima tj. berzama o ovoj temi. Molimo Vas za strplienje, jer još uvek nećemo davati izjave o podršsci od strane individualnih exchange-ova.',
    'zh_CN': '就目前而言，我们正在积极地与各个交易平台进行沟通。我们现在还不会发布关于哪个交易平 台会支持分叉的申明，请耐心等待。'
  },
  'faq-how-mine-title': {
    'ar': 'كيف أنقب عن ال"زيكلاسيك"',
    'es': '¿Cómo extraigo ZCL?',
    'fr': 'Comment miner du ZCL?',
    'he': 'כיצד "לכרות" ZCL?',
    'hu': 'Hogyan bányászhatok ZCL-t?',
    'id': 'Bagaimana saya menambang ZCL?',
    'ms': 'Bagaimana cara untuk melombong ZCL?',
    'nl': 'Hoe mine ik ZCL?',
    'sr': 'Kako rudarim (mine) ZCL?',
    'zh_CN': '如何挖矿ZCL?'
  },
  'faq-how-mine-text': {
    'ar': '<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"هنا تجد دليل التنقيب. كما أن التنقيب عن "بتكوين برايفت" سيكون مشابه. ترقب المزيد لاحقا.</a>',
    'es': 'Aquí hay una guía para minar ZCL en miningpoolhub. BTCP también será extraído de manera similar. <a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"Estén atentos para más información</a>.',
    'fr': '<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"Ici se trouve un guide pour miner du ZCL sur miningpoolhub</a>. BTCP sera aussi miné de la même façon. Restez connecté pour de plus amples informations.',
    'he': '<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"מצ"ב מדריך לכריית מטבע ZCL ב-miningpoolhub. מטבע ה-BTCP "ייכרה" באופן דומה. הישאר/י מעודכן/נת לקבלת מידע נוסף.</a>',
    'hu': '<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"Itt található az útmutató ZCL bányászáshoz a miningpoolhub-on</a>. A BTCP is hasonló módon bányászható. Légy készen további információkért.',
    'id': '<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"Ini adalah panduang untuk menambang ZCL di miningpoolhub.</a> BTCP juga akan ditambang dengan cara yang mirip. Terus simak web ini untuk informasi lebih lanjut.',
    'ms': '<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"Berikut adalah panduan untuk melombong ZCL di miningpoolhub</a>. BTCP juga akan dilombong dengan cara yang sama. Nantikan maklumat selanjutnya.',
    'nl': '<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"Hier is een beschrijving voor het minen van ZCL via miningpoolhub</a>. BTCP zal op vergelijkbare manier kunnen worden gemined. Meer informatie volgt.',
    'sr': '<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"Ovo je uputstvonkako da rudarite ZCL na miningpoolhub.com</a>. BTCP će biti rudaren na isti odnosno sličan način. Pratite nas za više informacija.',
    'zh_CN': '这里有一份在<a href="https://www.reddit.com/r/ZClassic/comments/7mfmyb/how_to_mine_zcl_using_nvidia_or_amd_gpus_on/?ref=share&ref_source=link" target="_blank"mingingpoolhub上的挖ZCL指南</a>。BTCP将会有类似的挖矿方式。保持更新以 获得更多详情。'
  },
  'faq-where-buy-title': {
    'ar': 'أين يمكن شراء عملة "زيكلاسيك"',
    'es': '¿Dónde puedo comprar ZCL en este momento?',
    'fr': 'Où peut on acheter du ZCL maintenant ?',
    'he': 'היכן ניתן לרכוש את המטבע ZCL?',
    'hu': 'Jelenleg hol lehet ZCL-t venni?',
    'id': 'Dimana saya bisa membeli ZCL sekarang?',
    'ms': 'Bagaimana cara untuk melombong ZCL?',
    'nl': 'Waar kan ik ZCL kopen?',
    'sr': 'Gde trenutno mogu kupiti ZCL?',
    'zh_CN': '现在哪里可以买ZCL?'
  },
  'faq-where-buy-text': {
    'ar': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> e <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'es': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> y <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'fr': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> et <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'he': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a>, <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'hu': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> és <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'id': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> dan <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'ms': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> and <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'nl': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> en <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'sr': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> i <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>',
    'zh_CN': '<a href="https://bittrex.com/Market/Index?MarketName=BTC-ZCL" target="_blank"Bittrex</a>, <a href="https://www.cryptopia.co.nz/Exchange?market=ZCL_BTC" target="_blank"Cryptopia</a> 和 <a href="https://www.coinexchange.io/market/ZCL/BTC" target="_blank"Coinexchange.io</a>'
  },
  'faq-how-development-title': {
    'ar': 'كيف يمكنني المساعدة في تطوير "بتكوين برايفت" ؟',
    'es': '¿Cómo puedo ayudar con el desarrollo de BTCP?',
    'fr': 'Comment puis-je aider dans le développement du BTCP?',
    'he': 'איך אוכל לעזור עם הפיתוח של BTCP?',
    'hu': 'Hogyan segíthetek a BTCP fejlesztésében?',
    'id': 'Bagaimana saya bisa membantu pengembangan BTCP?',
    'ms': 'Bagaimana saya boleh membantu membangunkan BTCP?',
    'nl': 'Hoe kan ik helpen met de ontwikkeling van BTCP?',
    'sr': 'Kako mogu pomoći razvijanju BTCP?',
    'zh_CN': '我如何参与帮助BTCP的开发？'
  },
  'faq-how-development-text': {
    'ar': '<a href="https://github.com/BTCPrivate/BitcoinPrivate/issues" target="_blank"ادخل على رابط github واقرأ المشاكل التي يواجهها المطورون في الوقت الحالي.</a>',
    'es': '<a href="https://github.com/BTCPrivate/BitcoinPrivate/issues" target="_blank"Vea los problemas publicados en github que necesitamos resolver para BTCP.</a>',
    'fr': 'Allez voir les problémes postés <a href="https://github.com/BTCPrivate/BitcoinPrivate/issues" target="_blank"sur github</a> que nous avons besoin de résoudre pour le BTCP.',
    'he': '<a href="https://github.com/BTCPrivate/BitcoinPrivate/issues" target="_blank"ראה/י את הבעיות שפורסמו ב-github שצריכות להפתר עבור BTCP.</a>',
    'hu': 'A BTCP megoldásra váró kérdésiet / feladatokat megtekintheted <a href="https://github.com/BTCPrivate/BitcoinPrivate/issues" target="_blank"a github-on megosztva</a>.',
    'id': 'Lihat <a href="https://github.com/BTCPrivate/BitcoinPrivate/issues" target="_blank"isu-isu di github</a> yang kami butuh bantuan untuk BTCP.',
    'ms': 'Lihat <a href="https://github.com/BTCPrivate/BitcoinPrivate/issues" target="_blank"isu yang dipaparkan di github</a> yang kami perlukan bantuan untuk BTCP.',
    'nl': 'Bekijk hier de <a href="https://github.com/BTCPrivate/BitcoinPrivate/issues" target="_blank"issues geplaatst op github</a> die nog moeten worden opgelost voor BTCP.',
    'sr': 'Pogledajte zadatke postavljene na github koji se trenutno trebaju odraditi.',
    'zh_CN': '参见发布在github上那些BTCP需要解决的issues.'
  },
  'faq-where-store-title': {
    'ar': 'أين يمكن الاحتفاظ بعملة "زيكلاسيك" ؟',
    'es': '¿Dónde puedo guardar mi ZCL para asegurarme de obtener mi BTCP?',
    'fr': 'Où puis-je stocker mon ZCL pour être certain d’obtenir mon BTCP?',
    'he': 'איפה אני יכול/ה לאחסן את מטבעות ה-ZCL שלי כדי להבטיח שאני מקבל/ת BTCP?',
    'hu': 'Hol tároljam a meglévő ZCL-t hogy biztosan megkapjam a BTCP-t?',
    'id': 'Dimana saya bisa menyimpan ZCL untuk memastikan saya mendapat BTCP?',
    'ms': 'Di mana saya boleh menyimpan ZCL untuk memastikan saya menerima BTCP saya?',
    'nl': 'Waar kan ik mijn ZCL bewaren om er zeker van te zijn dat ik mijn BTCP krijg?',
    'sr': 'Gde mogu držatu moje ZCL da bih se osigurao da ću dobiti BTCP?',
    'zh_CN': '我需要在哪里保存ZCL才能确保获得BTCP?'
  },
  'faq-where-store-text': {
    'ar': '<a href="https://redd.it/7kynho" target="_blank"الرجاء الاطلاع على دليل الاستخدام. بينما تواجهنا حاليا مشاكل بسيطة في المحفظة الحالية، نعدكم بمحافظ تعمل بنسبة ١٠٠٪ لأنظمة تشغيل "وندوز" و "ماك" قبل إتمام المشروع .</a>',
    'es': 'Utilice la siguiente guía simple sobre cómo <a href="https://redd.it/7kynho" target="_blank"instalar la billetera de Windows</a>. Si bien ha habido algunos problemas con la billetera ZCL actual, le prometemos que se liberará una billetera que funcione al 100% para Mac y Windows antes de el Hard Fork.',
    'fr': 'Utilisez ici notre guide pour savoir comment <a href="https://redd.it/7kynho" target="_blank"installer le wallet pour Windows</a>. Même s’il y a eu des problèmes avec l’actuel Wallet ZCL, nous vous promettons un wallet qui fonctionnera à 100% pour Mac et Windows et qui sera distribué avant le fork.',
    'he': '<a href="https://redd.it/7kynho" target="_blank"אנא השתמש/י במדריך הבא על אופן התקנת ארנק Windows. אמנם קיימות מספר בעיות עם הארנק הנוכחי של ZCL, אך אנו מבטיחים כי לפני הפיצול תשוחרר גרסה עובדת ב-100% עבור Mac ו-Windows.</a>',
    'hu': 'Kérlek használd a következő útmutatót: <a href="https://redd.it/7kynho" target="_blank"hogyan telepítsem a Windows pénztárcát</a>. Amíg volt néhány probléma a jelenlegi ZCL pénztárcával, ígérhetjük egy 100%-ban működő pénztárca kiadását Mac-re és Windows-ra még a “fork”-ot megelőzően.',
    'id': 'Silakan gunakan panduan sederhana ini untuk <a href="https://redd.it/7kynho" target="_blank"bagaimana menginstall dompet di windows</a>. Meskipun ada beberapa isu dengan dompet ZCL versi sekarang, kami menjamin bahwa dompet yang 100% berfungsi untuk Mac dan Windows akan dirilis sebelum fork.',
    'ms': 'Sila gunakan panduan ringkas berikut mengenai <a href="https://redd.it/7kynho" target="_blank"cara memasang dompet di Windows</a>. Walaupun terdapat beberapa isu dengan dompet ZCL versi sekarang, kami berjanji bahawa dompet yang berfungsi 100% untuk Mac dan Windows akan dikeluarkan sebelum fork.',
    'nl': 'U kunt deze eenvoudige handleiding gebruiken: “<a href="https://redd.it/7kynho" target="_blank"Hoe installeer ik de Windows wallet?</a>” Op dit moment zijn er wat problemen met de huidige ZCL wallet. We garanderen dat voor de hard fork een 100% werkende wallet beschikbaar zal zijn.',
    'sr': 'Molimo vas da iskoristite ovo jednostavno uputstvo kako da instalirate windows wallet. Trenutno još uvijek postoje neki problemi sa trenutnim ZCL wallet-om, ali obećavamo da će wallet za Mac i Windows koji 100% radi biti objavljen prije fork-a.',
    'zh_CN': '请参照该指南<a href="https://redd.it/7kynho" target="_blank"如何安装windows wallet</a>. 当前的ZCL钱包可能还存在一些小问题，但是我们保 证Windows和Mac钱包将会在分叉前100%运作正常。'
  },
  'faq-get-involved-title': {
    'ar': 'كيف أشارك في ال “فورك” ؟',
    'es': '¿Cómo me involucro en el Hard Fork?',
    'fr': 'Comment puis-je m’investir dans le fork?',
    'he': 'איך אני יכול/ה להיות מעורב בפיצול?',
    'hu': 'Hogyan vehetek részt a “fork”-ban?',
    'id': 'Bagaimana cara saya bisa terlibat dalam fork ini?',
    'ms': 'Bagaimana cara untuk saya turut serta di dalam fork ini?',
    'nl': 'Hoe raak ik betrokken bij de fork?',
    'sr': 'Kako da se uključim u fork?',
    'zh_CN': '我如何参与这次分叉？'
  },
  'faq-get-involved-text': {
    'ar': '<a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"أدخل على هذا الرابط واكتب تعليق (ارغب في المشاركة).</a>',
    'es': '<a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"Por favor, mira el enlace aquí y comenta para participar.</a>',
    'fr': '<a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"Vous trouverez ici les liens et commentaires pour vous investir.</a>',
    'he': '<a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"עיין בהתכתבות כאן וציין/ני כי ברצונך להיות מעורב/ת.</a>',
    'hu': '<a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"Kérlek tekintsd meg a thread-et itt és szólj hozzá, vegyél benne részt.</a>',
    'id': 'Silakan lihat <a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"thread ini</a> dan berikan komentar untuk terlibat.',
    'ms': 'Sila lihat <a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"thread ini</a> dan komen untuk turut serta.',
    'nl': 'Bekijk de <a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"thread hier</a> en reageer om mee te doen.',
    'sr': '<a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"Molimo vas pogledajte ovu objavu i komentarišite da biste se uključili.</a>',
    'zh_CN': '请浏览<a href="https://www.reddit.com/r/ZClassic/comments/7kt1ge/call_for_bitcoin_private_fork_volunteers/" target="_blank"这里的帖子</a>并参与评论进行参与。'
  },
  'faq-after-fork-title': {
    'ar': 'ماذا سيحدث ل"زيكلاسيك" بعد ال"فورك" ؟',
    'es': '¿Qué le sucede a ZCL después del Hard Fork?',
    'fr': 'Que deviendra ZCL après le fork ?',
    'he': 'מה יקרה ל- ZCL אחרי הפיצול?',
    'hu': 'Mi történik a ZCL-el a “fork” után?',
    'id': 'Apa yang akan terjadi pada ZCL setelah fork?',
    'ms': 'Apa yang akan terjadi kepada ZCL selepas fork?',
    'nl': 'Wat gebeurt er met ZCL na de fork?',
    'sr': 'Šta će biti sa ZCL nakon forka?',
    'zh_CN': 'ZCL在分叉后将会怎样？'
  },
  'faq-after-fork-text': {
    'ar': 'ستبقى "زيكلاسيك" موجودة. كما أن المشاركين قد تناولوا كيفية الحفاظ على "زيكلاسيك" وإبقائها في سلك التطوير المستمر بعد ال"فورك". نحن ندعم هذا الأمر ونستبشر به الخير.',
    'es': 'ZClassic todavía existirá. La comunidad ha discutido mantener ZCL en desarrollo activo después de El Hard Fork. Creemos que esto es grandioso y lo apoyamos completamente.',
    'fr': 'ZClassic existera toujours. La communauté a décidé de garder ZCL dans un développement actif après le fork. Nous pensons que cela est utile et nous continuerons à soutenir ce projet.',
    'he': 'ZClassic עדיין יהיה קיים. הקהילה דנה לשמר את המטבע בפיתוח פעיל גם לאחר הפיצול. אנחנו חושבים שזה נהדר ותומכים ברעיון באופן מלא.',
    'hu': 'A ZClassic megmarad. A közösség megállapodott a ZCL aktív fejlesztésében a ”fork” után. Nagyszerűnek tartjuk és teljes mértékben támogatjuk.',
    'id': 'ZClassic akan tetap ada. Kami dalam komunitas telah mendiskusikan mengenai pengembangan aktif ZCL sesudah fork. Kami berpikir bahwa ini bagus dan sangat mendukungnya.',
    'ms': 'ZClassic akan tetap wujud. Komuniti telah berbincang akan tetap memelihara dan terus aktif membangunkan ZCL selepas fork. Kami fikir hal ini bagus dan menyokong sepenuhnya.',
    'nl': 'ZClassic zal blijven bestaan. De community heeft besloten ZCL actief te blijven ontwikkelen na de fork. Dit vinden wij geweldig en blijven dit volledig ondersteunen.',
    'sr': 'ZClassic će i dalje postojati. Zajednica je izrazila želju da ZCL ostane u aktivnom razvijanj nakon forka. Mi mislimo da je ova ideja sjajna i u potpunosti je podržavamo i saglasni smo s njom.',
    'zh_CN': 'ZCL会照样存在。社区对此进行了讨论，并认为保持对分叉后的ZCL进行持续活跃开发。我们 高度认同并会全力支持。'
  },
  'faq-replay-protection-title': {
    'ar': 'هل ستتوفر تقنية التحقق الثنائي "ريبلاي بروتيكشن" في "بتكوين برايفت؟',
    'es': '¿Habrá protección de reproducción?',
    'fr': 'Y-aura-t-il le “Replay Protection” ?',
    'he': 'האם תהיה הגנה חוזרת?',
    'hu': 'Lesz “replay protection”?',
    'id': 'Apakah akan ada perlindungan replay?',
    'ms': 'Adakah ia akan mempunyai perlindungan replay?',
    'nl': 'Ondersteund BTCP replay-protectie?',
    'sr': 'Da li će biti replay protection?',
    'zh_CN': '会有(replay protection)重放攻击保护吗？'
  },
  'faq-replay-protection-text': {
    'ar': 'نعم تقنية التحقق الثنائى (two-way replay protection) ستكون متوفرة في "بتكوين برايفت".',
    'es': 'Sí, Bitcoin Private tendrá protección de repetición bidireccional.',
    'fr': 'Oui, Bitcoin Private aura un “Two-way Replay Protection”.',
    'he': 'כן, ל-Bitcoin Private תהיה הגנה חוזרת דו כיוונית.',
    'hu': 'Igen, a Bitcoin Private-nek lesz “two-way replay protection”.',
    'id': 'Ya, Bitcoin Private akan memiliki perlindungan replay 2-arah.',
    'ms': 'Ya, Bitcoin Private akan mempunyai perlindungan replay dua-arah.',
    'nl': 'Ja, Bitcoin Private heeft two-way replay protection.',
    'sr': 'Da, Bitcoin Private će imati replay protection u oba smera.',
    'zh_CN': '有，Bitcoin Private会有双向重放攻击保护(two-way replay protection).'
  },
  'resources-header-title': {
    'ar': 'BTCP موارد',
    'es': 'Recursos de BTCP',
    'fr': 'BTCP  Ressources',
    'he': 'משאבי BTCP',
    'hu': 'BTCP Források',
    'id': 'Sumber-sumber BTCP',
    'ms': 'Sumber BTCP',
    'nl': 'BTCP Bronnen',
    'sr': 'BTCP Resursi',
    'zh_CN': 'BTCP资源'
  },
  'resources-zclassic-cap-title': {
    'ar': 'ZCLassic Market Cap',
    'es': 'ZClassic Marke',
    'fr': 'ZClassic Market Cap',
    'he': 'שווי שוק ZClassic',
    'hu': 'ZClassic Market Cap',
    'id': 'Kapitalisasi Pasar ZClassic',
    'ms': 'Permodalan Pasaran ZClassic',
    'nl': 'ZClassic beurswaarde.',
    'sr': 'ZClassic Market Cap',
    'zh_CN': 'Zclassic市场总值'
  },
  'resources-zclassic-cap-text': {
    'ar': 'في الأسفل قيمة “زيكلاسيك” الحالية ورأس المال',
    'es': 'A continuación se muestra el precio de cotización actual de ZClassic y su capitalización bursátil.',
    'fr': 'Ci-dessous vous trouverez le cours du ZClassic ainsi que son market cap.',
    'he': 'להלן מחיר המסחר הנוכחי של המטבע ZClassic ואת שווי השוק שלו.',
    'hu': 'Alább található a ZClassic jelenlegi kereskedési ára és a piaci kapitalizáció.',
    'id': 'Di bawah ini adalah harga ZClassic saat ini dan kapitalisasi pasarnya.',
    'ms': 'Berikut adalah harga dagangan semasa ZClassic dan permodalan pasarannya.',
    'nl': 'Onderstaand is de huidige koers van ZClassic en de beurswaarde.',
    'sr': 'Ispod možete naći trenutnu cenu ZClassic-a i njegovu marke cap.',
    'zh_CN': '下面是当前Zclassic的交易价格和市场总值。'
  },
  'resources-press-inquiries-title': {
    'ar': 'استفسارات صحافية',
    'es': 'Preguntas de la prensa',
    'fr': 'Renseignements pour la presse',
    'he': 'פנה לעיתונות',
    'hu': 'Sajtó Megkeresések',
    'id': 'Pertanyaan Pers',
    'ms': 'Pertanyaan Media',
    'nl': 'Persverzoeken',
    'sr': 'Za medije',
    'zh_CN': '媒体联系'
  },
  'resources-press-inquiries-text': {
    'ar': 'للتواصل مع منظمين الفريق لما يخص الصحافة والنشر عن طريق تويتر <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a>',
    'es': 'Para ponerse en contacto con los coordinadores principales del equipo para cualquier consulta relacionada con la prensa, contáctenos en Twitter <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a>.',
    'fr': 'Pour contacter les principaux coordinateurs de l’équipe concernant toute question relative à la presse,  veuillez nous contacter sur Twitter <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate.</a>',
    'he': 'כדי ליצור קשר עם מתאם הראשי של הצוות עבור בירורים הקשורים לעיתונות,  אנא צרו איתנו קשר בטוויטר <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a>.',
    'hu': 'Az elsődleges csapat koordinátorok eléréséhez bármilyen sajtóval kapcsolatos megkeresésben, kérlek lépj velünk kapcsolatba a Twitter-en <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a>.',
    'id': 'Silakan kontak kami di twitter <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a> untuk menghubungi koordinator utama tim untuk semua pertanyaan terkait pers. ',
    'ms': 'Untuk menghubungi penyelaras utama pasukan bagi sebarang pertanyaan berkaitan media, sila hubungi kami di Twitter <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a>.',
    'nl': 'Om contact op te nemen met de coördinatoren van het team, voor pers gerelateerde zaken, maakt u het beste gebruik van Twitter via: <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a>.',
    'sr': 'Da biste nas kontaktirali sa bilo kakvim pitanjima vezanim za medije, molimo Vas da nam se obratite preko Twitter-a <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a>',
    'zh_CN': '如有任何媒体发布相关的问题和事宜想与团队主要协调人员取得联系，请联系 Twitter账号 <a href="https://twitter.com/bitcoinprivate" target="_blank"@bitcoinprivate</a>'
  },
  'resources-press-kit-title': {
    'ar': 'تحميل (Press Kit)',
    'es': 'Carpeta de prensa',
    'fr': 'Kit pour la presse',
    'he': 'מיתוג',
    'hu': 'Promóciós Szett',
    'id': 'Kit Pers',
    'ms': 'Kit Media',
    'nl': 'Persmap',
    'sr': 'Press Kit',
    'zh_CN': '媒体素材'
  },
  'resources-press-kit-text': {
    'ar': '<a href="presskit/presskit.zip" download>لتحميل نسخة مضغوطة لموارد "بتكوين برايفت" اضغط هنا.</a>',
    'es': '<a href="presskit/presskit.zip" download>Puede descargar un archivo zip que contiene los activos de marca de Bitcoin Private aquí.</a>',
    'fr': '<a href="presskit/presskit.zip" download>Vous pouvez télécharger un fichier ZIP contenant les principaux atouts du Bitcoin Private ici.</a>',
    'he': '<a href="presskit/presskit.zip" download>ניתן להוריד קובץ zip המכיל את המיתוג של Bitcoin Private כאן.</a>',
    'hu': '<a href="presskit/presskit.zip" download>Itt töltheted le a Bitcoin Private’s “branding” eszközöket tartalmazó zip fájlt.</a>',
    'id': '<a href="presskit/presskit.zip" download>You can download a zip file containing Bitcoin Private\'s branding assets here.</a>',
    'ms': '<a href="presskit/presskit.zip" download>Anda boleh muat turun file zip berisi aset penjenamaan Bitcoin Private di sini.</a>',
    'nl': '<a href="presskit/presskit.zip" download>U kunt hier een zip-file met de merk-items van Bitcoin Private downloaden.</a>',
    'sr': '<a href="presskit/presskit.zip" download>Možete preuzeti zip fajl sa Bitcoin Private brending sredstvima  ovde.</a>',
    'zh_CN': '<a href="presskit/presskit.zip" download>此处可下载Bitcoin Private的品牌素材压缩文件</a>'
  },
  'resources-official-links-title': {
    'ar': 'الروابط الرسمية',
    'es': 'Enlaces oficiales',
    'fr': 'Liens officiels',
    'he': 'קישורים רשמיים',
    'hu': 'Hivatalos linkek',
    'id': 'Link resmi',
    'ms': 'Pautan Rasmi',
    'nl': 'Officiële links',
    'sr': 'Службене везе',
    'zh_CN': '官方链接'
  },
  'resources-official-links-text': {
    'ar': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">يمكنك عرض دليل الرسمي بيتكوين الروابط الخاصة هنا.</a>',
    'es': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">Puede ver un directorio de enlaces privados de Bitcoin aquí.</a>',
    'fr': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">You can view a directory of official Bitcoin Private links here.</a>',
    'he': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">אתה יכול להציג ספרייה של קישורים רשמיים Bitcoin פרטיות כאן.</a>',
    'hu': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">You can view a directory of official Bitcoin Private links here.</a>',
    'id': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">Anda dapat melihat direktori tautan resmi Bitcoin Pribadi di sini.</a>',
    'ms': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">Anda boleh melihat direktori pautan peribadi Bitcoin Persendirian di sini.</a>',
    'nl': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">U kunt hier een lijst met officiële Bitcoin Private-links bekijken.</a>',
    'sr': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">Овде можете погледати каталог званичних Битцоин Приватних линкова.</a>',
    'zh_CN': '<a href="https://github.com/BTCP-community/official-links/blob/master/README.md" target="_blank">您可以在这里查看官方比特币私人链接的目录。'
  },
  'resources-social-title': {
    'ar': 'التواصل الاجتماعي',
    'es': 'Somos Sociales',
    'fr': 'Nous sommes aussi présents sur les réseaux sociaux',
    'he': 'חפשו אותנו ברשתות החברתיות',
    'hu': 'Közösségi Média',
    'id': 'Kami Sosial',
    'ms': 'We\'re Social',
    'nl': 'Volg Ons Op ',
    'sr': 'Društveni Smo',
    'zh_CN': '我们的社交网络'
  }
};

/*
'': {
  'ar': '',
  'es': '',
  'fr': '',
  'he': '',
  'hu': '',
  'id': '',
  'ms': '',
  'nl': '',
  'sr': '',
  'zh_CN': ''
}
*/
